# Render blueprint for Flask demo lab
# Students can edit this file to customize container deployment

services:
  - type: web                  # Web service (Flask app)
    name: flask-demo-lab       # Name of the service in Render
    env: docker                # Use Docker container
    branch: main               # Branch to deploy from
    dockerfilePath: Dockerfile # Path to Dockerfile (root of repo)
    plan: free                 # Free tier for students

    # Build & start commands for Docker
    buildCommand: docker build -t flask-demo-lab .
    startCommand: docker run -p 10000:5000 flask-demo-lab

    # Environment variables
    envVars:
      - key: FLASK_ENV
        value: 
      - key: SECRET_KEY
        value: "CHANGE_THIS_TO_A_SECRET"  # Students should change this

    # Health check for monitoring container
   # healthCheckPath: /health
   # healthCheckIntervalSeconds: 60       # Check every 60 seconds
   # healthCheckTimeoutSeconds: 5         # Timeout after 5 seconds
   # healthCheckHealthyThreshold: 1       # Healthy after 1 success
   # healthCheckUnhealthyThreshold: 3     # Unhealthy after 3 failures

    # Optional: mount a volume for persistent storage
    # Students can uncomment the next lines if they want to store files
    # volumes:
    #   - name: flask-data
    #     mountPath: /app/data
# Notes for students:
# 1.	The /health endpoint in app.py must exist; otherwise, Render will mark the container as unhealthy.
# 2.	SECRET_KEY should be updated per student for security.
# 3.	Optional volume mounting allows storing uploaded files or logs persistently.
# 4.	The docker run -p 10000:5000 maps container port 5000 to Render port 10000 — students don’t need to change this for now.

